
const restaurantData = [
  { id: 1,
    restaurantName: "The Funky Chicken",
    address: "4, Mermaid Quay, Cardiff CF10 5BZ",
    lat: 48.8737815,
    long: 2.3501649,
    ratings: [
      { ratingID: 1,
        stars: 2,
        comment: "Terrible service, not so funky! Yikes!",
      },
      { ratingID: 2,
        stars: 1,
        comment:
          "OMG, why did they chuck Carly out, it wasn't even her fault chicken was all over the floor",
      },
      { ratingID: 3,
        stars: 5,
        comment: "Great guys, GREAT CHICKEN",
      },
      { ratingID: 4,
        stars: 4,
        comment:
          "If you are after dirt cheap meat after a night out, this is the place",
      },
      {
        ratingID: 5,
        stars: 5,
        comment: "Los Pollos Hermanes",
      },
    ],
  },

  { id: 2,
    restaurantName: "K.F.Seafood",
    address: "2 W Bute St, Cardiff CF10 5EP",
    lat: 48.8737815,
    long: 2.3501649,
    ratings: [
      { ratingID: 1,
        stars: 2,
        comment: "There's something fishy about this place",
      },
      { ratingID: 2,
        stars: 5,
        comment: "Salmon please save me from myself!  Great fish restaurant",
      },
      { ratingID: 3,
        stars: 5,
        comment: "Great guys, GREAT FISH",
      },
      { ratingID: 4,
        stars: 4,
        comment: "cRAB LINGUINI WAS TO DIE FOR!!!1!",
      },
    ],
  },

  { id: 3,
    restaurantName: "Kevin Vegan",
    address: "3 Havannah St, Cardiff CF10 5SF",
    lat: 48.8865035,
    long: 2.3442197,
    ratings: [
      { ratingID: 1,
        stars: 4,
        comment: "God Cress this place",
      },
      { ratingID: 2,
        stars: 5,
        comment: "SWEET! (potato)",
      },
      { ratingID: 3,
        stars: 5,
        comment: "Lettuce eat here every week from now on!",
      },
      { ratingID: 4,
        stars: 4,
        comment: "onYUM",
      },
    ],
  },

  { id: 4,
    restaurantName: "Papa Joans",
    address: "1 Ferry Road Cardiff Bay Retail Park",
    lat: 48.8865035,
    long: 2.3442197,
    ratings: [
      { ratingID: 1,
        stars: 4,
        comment: "Why isn't it called Mama Joans?  Good food though",
      },
      { ratingID: 2,
        stars: 5,
        comment:
          "Loooooove the meatfeast, its so like the one i had in New York",
      },
      { ratingID: 3,
        stars: 5,
        comment: "Lil Slice of Heaven",
      },
      { ratingID: 4,
        stars: 2,
        comment: "poor service, poorer food",
      },
    ],
  },

  { id: 5,
    restaurantName: "Where it all Vegan",
    address: "1 Hemingway Rd, Cardiff CF10 4JY",
    lat: 48.8865035,
    long: 2.3442197,
    ratings: [
      { ratingID: 1,
        stars: 5,
        comment: "great imitation burgers, much better than beyond burgers",
      },
      { ratingID: 2,
        stars: 5,
        comment: "I would give this six stars if i could!",
      },
      { ratingID: 3,
        stars: 5,
        comment: "Talk of the town, much better than Kevin Vegan!",
      },
      { ratingID: 4,
        stars: 5,
        comment: "WOW, this food is dangerously good!",
      },
      { ratingID: 5,
        stars: 5,
        comment: "So impressive how like meat this tastes",
      },
      { ratingID: 6,
        stars: 4,
        comment: "yummy veggies in my tummy",
      },
    ],
  },

  { id: 6,
    restaurantName: "Pizza Hat",
    address: "Cardiff CF11 0JP",
    lat: 48.8865035,
    long: 2.3442197,
    ratings: [
      { ratingID: 1,
        stars: 4,
        comment: "I was NOT expecting them to be wearing pizza on their head!",
      },
      { ratingID: 2,
        stars: 2,
        comment: "I was expecting them to be wearing pizza on their head!",
      },
      { ratingID: 3,
        stars: 5,
        comment: "oooooof that pizza is licious",
      },
      { ratingID: 4,
        stars: 4,
        comment: "omnom nom nom nom pepperoni nom nom om",
      },
    ],
  },
];
export {restaurantData}
